display_name: fl_audiobook
package_name: fl-audiobook
maintainer:
  name: Rachel Volk
  email: rachel@mode13h.de
priority: optional
section: x11
installed_size: 6604
essential: false
icon: images/app_icon.png

postinstall_scripts:
  - echo "Installed my awesome app"
postuninstall_scripts:
  - echo "Surprised Pickachu face"

keywords:
  - Hello
  - World
  - Test
  - Application

generic_name: Audiobook Player

categories:
  - Media

startup_notify: true

startup_wm_class: fl-audiobook

# You can also specify [metainfo](https://freedesktop.org/software/appstream/docs/chap-Quickstart.html) file
# which contains metadata of the app.
metainfo: linux/packaging/fl-audiobook.appdata.xml